name: CI

on:
  push:
    branches:
      - master

env:
  REGISTRY: "hubulbib"
  IMAGE_NAME: "flint"
  CONTAINER_NAME: "hubulbib/flint"

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .

      - name: Log in to DockerHub
        run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}

      - name: Push image to DockerHub
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME
          script: |
            # Login into DockerHub
            docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
            # Stop running container
            docker stop $(echo $CONTAINER_NAME)
            # Remove old container
            docker rm $(echo $CONTAINER_NAME)
            # Pull latest image
            docker pull hubulbib/flint:latest
            # Run a new container from a new image
            docker run -d -p 80:80 --name $(echo $CONTAINER_NAME) $(echo $CONTAINER_NAME):latest 